SCENARIO_LIST = "/home/bes/pcm/ScenarioList.csv"
EXECUTE_LIST = "/home/bes/pcm/ExecuteList.csv"
EXECUTE_DIR = "/home/bes/pcm/tmp"
INPUT_DIR = "/home/bes/pcm/data/input"
OUTPUT_DIR = "/home/bes/pcm/data/output"
