SCENARIO_LIST = '/home/EGM/v2/ScenarioList.csv'
EXECUTE_LIST = '/home/EGM/v2/ExecuteList.csv'
EXECUTE_DIR = '/home/EGM/v2/tmp'
INPUT_DIR = '/home/EGM/v2/data/input'
OUTPUT_DIR = '/home/EGM/v2/data/output'
